name: Docker Image CI

on:
  # Cambios nuevos en main
  push:
    branches: ['main']
  # Cuando se abre un pull request a main
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    # Cada uno de los - es un paso
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker login
        # Aqui van los secrets de github
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        # Cada | es un salto de linea
        run: echo "Iniciando login" docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASSWORD echo "Fin del login"

      - name: Build Docker image
        run: docker build -t oskar823/docker-graphql:0.0.2 .

      - name: Push Docker image
        run: docker push oskar823/docker-graphql:0.0.2
