name: Docker Image CI

on:
  # Cambios nuevos en main
  push:
    branches: ['main']
  # Cuando se abre un pull request a main
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    # Cada uno de los - es un paso
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Un action del marketplace para generar versiones semanticas
      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: 'major:'
          minor_pattern: 'feat:'
          format: '${major}.${minor}.${patch}-prerelease${increment}'
        id: version

      - name: Docker login
        # Aqui van los secrets de github
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        # Cada | es un salto de linea
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Docker image
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: docker build -t oskar823/docker-graphql:$NEW_VERSION .

      - name: Push Docker image
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: docker push docker.io/oskar823/docker-graphql:$NEW_VERSION && docker push docker.io/oskar823/docker-graphql:latest
